const FUEL_GASOLINE = 'gasoline';
const FUEL_HYBRID = 'hybrid';
const FUEL_ELECTRIC = 'ev';
const SEGMENT_SMALL = 'C';
const SEGMENT_MEDIUM = 'D';
const SEGMENT_LARGE = 'E';
const SEGMENT_SUV = 'SUV';

export const CATEGORY = [
  FUEL_GASOLINE,
  FUEL_HYBRID,
  FUEL_ELECTRIC,
  SEGMENT_SMALL,
  SEGMENT_MEDIUM,
  SEGMENT_LARGE,
  SEGMENT_SUV,
];
